services:
  - type: web
    name: studentnest-web
    env: docker
    repo: https://github.com/Muhamedall/studentnest-fullstack-projct
    branch: main
    plan: starter
    dockerfilePath: Dockerfile
    buildCommand: ""       # Docker handles build
    startCommand: ""       # Docker CMD used (supervisor starts nginx+php-fpm)
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase: studentnest-db
      - key: DB_DATABASE
        fromDatabase: studentnest-db
      - key: DB_USERNAME
        fromDatabase: studentnest-db
      - key: DB_PASSWORD
        fromDatabase: studentnest-db

databases:
  - name: studentnest-db
    type: postgres
    plan: starter
